[env:lilygo-toiplus-esp32c3]
board = ttgo-t-oi-plus
platform = espressif32
framework = arduino
lib_deps = ESP32 BLE Arduino @ 2.0.0
monitor_speed = 115200
upload_speed = 921600

; temporary for development
; build_flags = -D PPK_DEBUG
; monitor_port = COM19
; upload_port = COM19